### ISSUE TITLE
The example code is in

### ISSUE THREAD

**Issue by 1stofhername** [learn-co-curriculum/phase-3-array-basics#2]
### Canvas Link

https://learning.flatironschool.com/courses/4619/pages/array-basics?module_item_id=344877

### Concern

shopping_list[0..1]
# => ["Cookies", "Mint Chocolate Chip Ice Cream"]
shopping_list[0...2]
# => ["Cookies", "Mint Chocolate Chip Ice Cream"]

### Suggested Changes

shopping_list[0...2]
should return:
# => ["Cookies", "Mint Chocolate Chip Ice Cream", "Snickers"]

**Comment by 1stofhername** [comment]
I see the second one is using three dots. I would advise having the second example be shopping_list[0...1] so that it's easier to see that the change is with the dot operator and how it changes the output.

**Comment by lizbur10** [comment]
Hi @1stofhername! Thanks for pointing this out - I have added a clarification. 💙
